config/routes.rb
Rails.application.routes.draw do
  #resources :attachments
  resources :attachments do
    collection { post :parse }
    collection { post :display_graphics }
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :measurement_groups
  resources :devices
  resources :measurements
  resources :samples
  resources :researchers
  resources :raw_datums
  resources :description_for_rds


  #resources :measurement_groups, shallow: true do
  #  resources :devices
  #end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
    validate :file_size_under_one_mb

  def initialize(params = {})
    @file = params.delete(:file)
    super
    if @file
      self.filename = sanitize_filename(@file.original_filename)
      self.content_type = @file.content_type
      self.file_contents = @file.read
    end
  end

  private

    def sanitize_filename(filename)
      # Get only the filename, not the whole path (for IE)
      # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
      return File.basename(filename)
    end

    NUM_BYTES_IN_MEGABYTE = 1048576
    def file_size_under_one_mb
      if (@file.size.to_f / NUM_BYTES_IN_MEGABYTE) > 1
        errors.add(:file, 'File size cannot be over one megabyte.')
      end
    end
end

app/models/description_for_rd.rb
class DescriptionForRd < ActiveRecord::Base
    self.table_name = 'description_for_rd'
    self.primary_key = :DescriptionForRdID

    belongs_to :raw_datum, :class_name => 'RawDatum', :foreign_key => :rdID
end

app/models/device.rb
class Device < ActiveRecord::Base

    self.primary_key = :deviceID

    has_many :measurement_groups, :class_name => 'MeasurementGroup', :foreign_key => :deviceID
end

app/models/linked.rb
class Linked < ActiveRecord::Base



    belongs_to :measurement, :class_name => 'Measurement', :foreign_key => :measurementID
    belongs_to :measurement_group, :class_name => 'MeasurementGroup', :foreign_key => :groupID
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base

    self.primary_key = :measurementID

    has_many :linkeds, :class_name => 'Linked', :foreign_key => :measurementID
    belongs_to :raw_datum, :class_name => 'RawDatum', :foreign_key => :rpID
    has_many :measurement_description_for_measurements, :class_name => 'MeasurementDescriptionForMeasurement', :foreign_key => :measurementID
end

app/models/measurement_group.rb
class MeasurementGroup < ActiveRecord::Base

    self.primary_key = :groupID

    has_many :linkeds, :class_name => 'Linked', :foreign_key => :groupID
    has_many :description_for_measurement_groups, :class_name => 'DescriptionForMeasurementGroup', :foreign_key => :groupID
    belongs_to :sample, :class_name => 'Sample', :foreign_key => :sampleID
    belongs_to :researcher, :class_name => 'Researcher', :foreign_key => :researcherID
    belongs_to :device, :class_name => 'Device', :foreign_key => :deviceID
    has_many :raw_data, :class_name => 'RawDatum', :foreign_key => :groupID
end

app/models/raw_datum.rb
class RawDatum < ActiveRecord::Base

    self.primary_key = :rdID

    has_many :measurements, :class_name => 'Measurement'
    has_many :description_for_rds, :class_name => 'DescriptionForRd', :foreign_key => :rdID
    belongs_to :measurement_group, :class_name => 'MeasurementGroup', :foreign_key => :groupID
end

app/models/researcher.rb
class Researcher < ActiveRecord::Base

    self.primary_key = :researcherID

    has_many :measurement_groups, :class_name => 'MeasurementGroup', :foreign_key => :researcherID
end

app/models/sample.rb
class Sample < ActiveRecord::Base

    self.primary_key = :sampleID

    has_many :measurement_groups, :class_name => 'MeasurementGroup', :foreign_key => :sampleID
end

app/models/schema_migration.rb
class SchemaMigration < ActiveRecord::Base



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def index
    @devices = Device.all
  end

  def new
    @device = Device.new
  end

  def edit
  @device = Device.find(params[:id])
  end

  def show
    @device = Device.find(params[:id])
  end

  def create
    @device = Device.new(device_params)

    if @device.save
    redirect_to @device
    else
    render 'new'
    end
  end

  def update
  @device = Device.find(params[:id])

  if @device.update(device_params)
    redirect_to @device
  else
    render 'edit'
  end
  end

  def destroy
  @device = Device.find(params[:id])
  @device.destroy

  redirect_to devices_path
end



  private
  def device_params
    params.require(:device).permit(:name, :manufacturer, :description, :model)
  end
end

app/controllers/measurement_groups_controller.rb
class MeasurementGroupsController < ApplicationController

  def index
    @measurement_groups = MeasurementGroup.all

  end

  def new
    @measurement_group = MeasurementGroup.new
    @researcher = Researcher.all
    @sample = Sample.all
    @device = Device.all
  end

  def edit
  @measurement_group = MeasurementGroup.find(params[:id])
  end

  def show
    @measurement_group = MeasurementGroup.find(params[:id])
    if @measurement_group.researcherID != nil
      @researcher = Researcher.find(@measurement_group.researcherID)
    end
    if @measurement_group.deviceID != nil
      @device = Device.find(@measurement_group.deviceID)
    end
    if @measurement_group.sampleID != nil
      @sample = Sample.find(@measurement_group.sampleID)
    end
  end

  def create
    @measurement_group = MeasurementGroup.new(measurement_group_params)

    if @measurement_group.save
    redirect_to @measurement_group
    else
    render 'new'
    end
  end

  def update
  @measurement_group = MeasurementGroup.find(params[:id])

  if @measurement_group.update(measurement_group_params)
    redirect_to @measurement_group
  else
    render 'edit'
  end
  end

  def destroy
  @measurement_group = MeasurementGroup.find(params[:id])
  @measurement_group.destroy

  redirect_to measurement_groups_path
end



  private
  def measurement_group_params
    params.require(:measurement_group).permit(:sampleID, :researcherID, :deviceID, :name, :date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/measurement_groups_helper.rb
module MeasurementGroupsHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/raw_datums_helper.rb
module RawDatumsHelper
end

app/helpers/researchers_helper.rb
module ResearchersHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/measurement_groups/_form.html.erb
<%= bootstrap_form_for @measurement_group do |f| %>

  <% if @measurement_group.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@measurement_group.errors.count, "error") %> prohibited
        this measurement_group from being saved:
      </h2>
      <ul>
        <% @measurement_group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :name, label: "Название" %>

    <%= f.date_select :date, label: "Дата создания" %>


    <%= f.collection_select(:sampleID, Sample.all, :id, :name,label: "Образец") %>
    <%= f.collection_select(:researcherID, Researcher.all, :id, :name,label: "Исследователь") %>
    <%= f.collection_select(:deviceID, Device.all, :id, :name,label: "Прибор") %>






    <%= f.submit %>


<% end %>

app/views/measurement_groups/edit.html.erb
<h1>Изменить</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= render 'form' %>
    <%= link_to 'Назад', measurement_group_path %>
    </div>
</div>

app/views/measurement_groups/index.html.erb
<h1>Группы измерений</h1>

  <td><a class='btn-primary'><%= link_to 'Добавить группу', new_measurement_group_path %></a></td>
<td><%= link_to 'Скачать отчет', "/measurement_groups.pdf" %></td></br></br></br>

<table class="table table-striped table-condensed">
  <tr>
    <th>Образец</th>
    <th>Исследователь</th>
    <th>Прибор</th>
    <th>Название группы</th>
    <th>Дата</th>

  </tr>

  <% @measurement_groups.each do |measurement_group| %>
    <tr>
      <% if measurement_group.sampleID != nil %>
      <td><%= Sample.find(measurement_group.sampleID).name %></td>
      <% end %>
      <% if measurement_group.researcherID != nil %>
      <td><%= Researcher.find(measurement_group.researcherID).name %></td>
      <% end %>
      <% if measurement_group.deviceID != nil %>
      <td><%= Device.find(measurement_group.deviceID).name %></td>
      <% end %>
      <td><%= measurement_group.name %></td>
      <td><%= measurement_group.date %></td>
      <td><%= link_to 'Показать', measurement_group_path(measurement_group) %></td>
      <td><%= link_to 'Изменить', edit_measurement_group_path(measurement_group) %></td>
      <td><%= link_to 'Удалить', measurement_group_path(measurement_group),
              method: :delete,
              data: { confirm: 'Вы уверены?' } %></td>
   </tr>
  <% end %>
</table>

app/views/measurement_groups/new.html.erb
<h1>Добавить группу</h1>
<div class="col-md-4 col-md-offset-4">
    <%= render 'form' %>
</div>

app/views/measurement_groups/show.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
  <h1>Группа измерений <%= @measurement_group.name %></h1>

    <p>
      <strong>Дата создания</strong>
      <%= @measurement_group.date %>
    </p>
    <% if @measurement_group.researcherID != nil %>
    <h2>Исследователь</h2>
    <p>
      <strong>Имя</strong>
      <%= @researcher.name %>
    </p>
    <p>
      <strong>Телефон</strong>
      <%= @researcher.phone %>
    </p>
    <p>
      <strong>Организация</strong>
      <%= @researcher.organizations %>
    </p>
    <p>
      <strong>Адрес</strong>
      <%= @researcher.address %>
    </p>
    <p>
      <strong>Email</strong>
      <%= @researcher.email %>
    </p>
    <% end %>

    <% if @measurement_group.deviceID != nil %>
    <h2>Прибор</h2>
    <p>
      <strong>Название прибора</strong>
      <%= @device.name %>
    </p>
    <p>
      <strong>Производитель</strong>
      <%= @device.manufacturer %>
    </p>
    <p>
      <strong>Характеристики</strong>
      <%= @device.description %>
    </p>
    <p>
      <strong>Модель</strong>
      <%= @device.model %>
    </p>
    <% end %>

    <% if @measurement_group.sampleID != nil %>
    <h2>Образец</h2>
    <p>
      <strong>Название образца</strong>
      <%= @sample.name %>
    </p>
    <p>
      <strong>Вес</strong>
      <%= @sample.weight %>
    </p>
    <p>
      <strong>Размер</strong>
      <%= @sample.size %>
    </p>
    <p>
      <strong>Масса</strong>
      <%= @sample.M %>
    </p>
    <p>
      <strong>Lambda em</strong>
      <%= @sample.lambda_em %>
    </p>
    <p>
      <strong>Lambda ex</strong>
      <%= @sample.lambda_ex %>
    </p>
    <p>
      <strong>Описание</strong>
      <%= @sample.description %>
    </p>
    <% end %>

    </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= link_to 'Назад', measurement_groups_path %> |
    <%= link_to 'Изменить', edit_measurement_group_path(@measurement_group) %>
    </div>
</div>