config/routes.rb
Rails.application.routes.draw do
  #resources :attachments
  resources :attachments do
    collection { post :parse }
    collection { post :display_graphics }
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :measurement_groups
  resources :devices
  resources :measurements
  resources :samples
  resources :researchers
  resources :raw_datums
  resources :description_for_rds


  #resources :measurement_groups, shallow: true do
  #  resources :devices
  #end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
    validate :file_size_under_one_mb

  def initialize(params = {})
    @file = params.delete(:file)
    super
    if @file
      self.filename = sanitize_filename(@file.original_filename)
      self.content_type = @file.content_type
      self.file_contents = @file.read
    end
  end

  private

    def sanitize_filename(filename)
      # Get only the filename, not the whole path (for IE)
      # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
      return File.basename(filename)
    end

    NUM_BYTES_IN_MEGABYTE = 1048576
    def file_size_under_one_mb
      if (@file.size.to_f / NUM_BYTES_IN_MEGABYTE) > 1
        errors.add(:file, 'File size cannot be over one megabyte.')
      end
    end
end

app/models/description_for_rd.rb
class DescriptionForRd < ActiveRecord::Base
    self.table_name = 'description_for_rd'
    self.primary_key = :DescriptionForRdID

    belongs_to :raw_datum, :class_name => 'RawDatum', :foreign_key => :rdID
end

app/models/device.rb
class Device < ActiveRecord::Base

    self.primary_key = :deviceID

    has_many :measurement_groups, :class_name => 'MeasurementGroup', :foreign_key => :deviceID
end

app/models/linked.rb
class Linked < ActiveRecord::Base



    belongs_to :measurement, :class_name => 'Measurement', :foreign_key => :measurementID
    belongs_to :measurement_group, :class_name => 'MeasurementGroup', :foreign_key => :groupID
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base

    self.primary_key = :measurementID

    has_many :linkeds, :class_name => 'Linked', :foreign_key => :measurementID
    belongs_to :raw_datum, :class_name => 'RawDatum', :foreign_key => :rpID
    has_many :measurement_description_for_measurements, :class_name => 'MeasurementDescriptionForMeasurement', :foreign_key => :measurementID
end

app/models/measurement_group.rb
class MeasurementGroup < ActiveRecord::Base

    self.primary_key = :groupID

    has_many :linkeds, :class_name => 'Linked', :foreign_key => :groupID
    has_many :description_for_measurement_groups, :class_name => 'DescriptionForMeasurementGroup', :foreign_key => :groupID
    belongs_to :sample, :class_name => 'Sample', :foreign_key => :sampleID
    belongs_to :researcher, :class_name => 'Researcher', :foreign_key => :researcherID
    belongs_to :device, :class_name => 'Device', :foreign_key => :deviceID
    has_many :raw_data, :class_name => 'RawDatum', :foreign_key => :groupID
end

app/models/raw_datum.rb
class RawDatum < ActiveRecord::Base

    self.primary_key = :rdID

    has_many :measurements, :class_name => 'Measurement'
    has_many :description_for_rds, :class_name => 'DescriptionForRd', :foreign_key => :rdID
    belongs_to :measurement_group, :class_name => 'MeasurementGroup', :foreign_key => :groupID
end

app/models/researcher.rb
class Researcher < ActiveRecord::Base

    self.primary_key = :researcherID

    has_many :measurement_groups, :class_name => 'MeasurementGroup', :foreign_key => :researcherID
end

app/models/sample.rb
class Sample < ActiveRecord::Base

    self.primary_key = :sampleID

    has_many :measurement_groups, :class_name => 'MeasurementGroup', :foreign_key => :sampleID
end

app/models/schema_migration.rb
class SchemaMigration < ActiveRecord::Base



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def index
    @devices = Device.all
  end

  def new
    @device = Device.new
  end

  def edit
  @device = Device.find(params[:id])
  end

  def show
    @device = Device.find(params[:id])
  end

  def create
    @device = Device.new(device_params)

    if @device.save
    redirect_to @device
    else
    render 'new'
    end
  end

  def update
  @device = Device.find(params[:id])

  if @device.update(device_params)
    redirect_to @device
  else
    render 'edit'
  end
  end

  def destroy
  @device = Device.find(params[:id])
  @device.destroy

  redirect_to devices_path
end



  private
  def device_params
    params.require(:device).permit(:name, :manufacturer, :description, :model)
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  def index
    @samples = Sample.all
  end

  def new
    @sample = Sample.new
  end

  def edit
  @sample = Sample.find(params[:id])
  end

  def show
    @sample = Sample.find(params[:id])
  end

  def create
    @sample = Sample.new(sample_params)

    if @sample.save
    redirect_to @sample
    else
    render 'new'
    end
  end

  def update
  @sample = Sample.find(params[:id])

  if @sample.update(sample_params)
    redirect_to @sample
  else
    render 'edit'
  end
  end

  def destroy
  @sample = Sample.find(params[:id])
  @sample.destroy

  redirect_to samples_path
end



  private
  def sample_params
    params.require(:sample).permit(:name, :weight, :size, :M, :lambda_em, :lambda_ex,
                                                        :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/raw_datums_helper.rb
module RawDatumsHelper
end

app/helpers/researchers_helper.rb
module ResearchersHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/devices/_form.html.erb
<%= form_for @device do |f| %>

  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@device.errors.count, "error") %> prohibited
        this device from being saved:
      </h2>
      <ul>
        <% @device.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :manufacturer %><br>
    <%= f.text_area :manufacturer %>
  </p>

  <p>
    <%= f.label :model %><br>
    <%= f.text_area :model %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/devices/edit.html.erb
<h1>Изменить данные</h1>

<%= render 'form' %>

<%= link_to 'Назад', devices_path %>

app/views/devices/index.html.erb
<h1>Список приборов</h1>

  <td><a class='btn-primary'><%= link_to 'Добавить прибор', new_device_path %></a></td>
<td><%= link_to 'Скачать отчет', "/devices.pdf" %></td></br></br></br>

<table class="table table-striped table-condensed">
  <tr>
    <th>Name</th>
    <th>Manufacturer</th>
    <th>Model</th>
    <th>Description</th>

  </tr>

  <% @devices.each do |device| %>
    <tr>
      <td><%= device.name %></td>
      <td><%= device.manufacturer %></td>
      <td><%= device.model %></td>
      <td><%= device.description %></td>
      <td><%= link_to 'Показать', device_path(device) %></td>
      <td><%= link_to 'Изменить', edit_device_path(device) %></td>
      <td><%= link_to 'Удалить', device_path(device),
              method: :delete,
              data: { confirm: 'Вы уверены?' } %></td>
   </tr>
  <% end %>
</table>

app/views/devices/new.html.erb
<%= render 'form' %>

app/views/devices/show.html.erb
<p>
  <strong>Name</strong>
  <%= @device.name %>
</p>

<p>
  <strong>Manufacturer</strong>
  <%= @device.manufacturer %>
</p>

<p>
  <strong>Model</strong>
  <%= @device.model %>
</p>

<p>
  <strong>Description</strong>
  <%= @device.description %>
</p>



<%= link_to 'Назад', devices_path %> |
<%= link_to 'Изменить', edit_device_path(@device) %>

app/views/samples/_form.html.erb
<%= form_for @sample do |f| %>

  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@sample.errors.count, "error") %> prohibited
        this sample from being saved:
      </h2>
      <ul>
        <% @sample.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :weight %><br>
    <%= f.text_area :weight %>
  </p>

  <p>
    <%= f.label :size %><br>
    <%= f.text_area :size %>
  </p>

  <p>
    <%= f.label :M %><br>
    <%= f.text_area :M %>
  </p>

  <p>
    <%= f.label :lambda_em %><br>
    <%= f.text_area :lambda_em %>
  </p>

  <p>
    <%= f.label :lambda_ex %><br>
    <%= f.text_area :lambda_ex %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/samples/edit.html.erb
<h1>Изменить данные</h1>

<%= render 'form' %>

<%= link_to 'Назад', samples_path %>

app/views/samples/index.html.erb
<h1>Список образцов</h1>

  <td><a class='btn-primary'><%= link_to 'Добавить образец', new_sample_path %></a></td>
<td><%= link_to 'Скачать отчет', "/samples.pdf" %></td></br></br></br>

<table class="table table-striped table-condensed">
  <tr>
    <th>Name</th>
    <th>Weight</th>
    <th>Size</th>
    <th>M</th>
    <th>Lambda_em</th>
    <th>Lambda_ex</th>
    <th>Description</th>
  </tr>

  <% @samples.each do |sample| %>
    <tr>
      <td><%= sample.name %></td>
      <td><%= sample.weight %></td>
      <td><%= sample.size %></td>
      <td><%= sample.M %></td>
      <td><%= sample.lambda_em %></td>
      <td><%= sample.lambda_ex %></td>
      <td><%= sample.description %></td>
      <td><%= link_to 'Показать', sample_path(sample) %></td>
      <td><%= link_to 'Изменить', edit_sample_path(sample) %></td>
      <td><%= link_to 'Удалить', sample_path(sample),
              method: :delete,
              data: { confirm: 'Вы уверены?' } %></td>
   </tr>
  <% end %>
</table>

app/views/samples/new.html.erb
<%= render 'form' %>

app/views/samples/show.html.erb
<p>
  <strong>Name</strong>
  <%= @sample.name %>
</p>

<p>
  <strong>Weight</strong>
  <%= @sample.weight %>
</p>

<p>
  <strong>Size</strong>
  <%= @sample.size %>
</p>

<p>
  <strong>M</strong>
  <%= @sample.M %>
</p>

<p>
  <strong>Lambda_em</strong>
  <%= @sample.lambda_em %>
</p>

<p>
  <strong>Lambda_ex</strong>
  <%= @sample.lambda_ex %>
</p>

<p>
  <strong>Description</strong>
  <%= @sample.description %>
</p>

<%= link_to 'Назад', samples_path %> |
<%= link_to 'Изменить', edit_sample_path(@sample) %>