config/routes.rb
Rails.application.routes.draw do
  #resources :attachments
  resources :attachments do
    collection { post :parse }
    collection { post :display_graphics }
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :measurement_groups
  resources :devices
  resources :measurements
  resources :samples
  resources :researchers
  resources :raw_datums
  resources :description_for_rds


  #resources :measurement_groups, shallow: true do
  #  resources :devices
  #end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
    validate :file_size_under_one_mb

  def initialize(params = {})
    @file = params.delete(:file)
    super
    if @file
      self.filename = sanitize_filename(@file.original_filename)
      self.content_type = @file.content_type
      self.file_contents = @file.read
    end
  end

  private

    def sanitize_filename(filename)
      # Get only the filename, not the whole path (for IE)
      # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
      return File.basename(filename)
    end

    NUM_BYTES_IN_MEGABYTE = 1048576
    def file_size_under_one_mb
      if (@file.size.to_f / NUM_BYTES_IN_MEGABYTE) > 1
        errors.add(:file, 'File size cannot be over one megabyte.')
      end
    end
end

app/models/description_for_rd.rb
class DescriptionForRd < ActiveRecord::Base
    self.table_name = 'description_for_rd'
    self.primary_key = :DescriptionForRdID

    belongs_to :raw_datum, :class_name => 'RawDatum', :foreign_key => :rdID
end

app/models/device.rb
class Device < ActiveRecord::Base

    self.primary_key = :deviceID

    has_many :measurement_groups, :class_name => 'MeasurementGroup', :foreign_key => :deviceID
end

app/models/linked.rb
class Linked < ActiveRecord::Base



    belongs_to :measurement, :class_name => 'Measurement', :foreign_key => :measurementID
    belongs_to :measurement_group, :class_name => 'MeasurementGroup', :foreign_key => :groupID
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base

    self.primary_key = :measurementID

    has_many :linkeds, :class_name => 'Linked', :foreign_key => :measurementID
    belongs_to :raw_datum, :class_name => 'RawDatum', :foreign_key => :rpID
    has_many :measurement_description_for_measurements, :class_name => 'MeasurementDescriptionForMeasurement', :foreign_key => :measurementID
end

app/models/measurement_group.rb
class MeasurementGroup < ActiveRecord::Base

    self.primary_key = :groupID

    has_many :linkeds, :class_name => 'Linked', :foreign_key => :groupID
    has_many :description_for_measurement_groups, :class_name => 'DescriptionForMeasurementGroup', :foreign_key => :groupID
    belongs_to :sample, :class_name => 'Sample', :foreign_key => :sampleID
    belongs_to :researcher, :class_name => 'Researcher', :foreign_key => :researcherID
    belongs_to :device, :class_name => 'Device', :foreign_key => :deviceID
    has_many :raw_data, :class_name => 'RawDatum', :foreign_key => :groupID
end

app/models/raw_datum.rb
class RawDatum < ActiveRecord::Base

    self.primary_key = :rdID

    has_many :measurements, :class_name => 'Measurement'
    has_many :description_for_rds, :class_name => 'DescriptionForRd', :foreign_key => :rdID
    belongs_to :measurement_group, :class_name => 'MeasurementGroup', :foreign_key => :groupID
end

app/models/researcher.rb
class Researcher < ActiveRecord::Base

    self.primary_key = :researcherID

    has_many :measurement_groups, :class_name => 'MeasurementGroup', :foreign_key => :researcherID
end

app/models/sample.rb
class Sample < ActiveRecord::Base

    self.primary_key = :sampleID

    has_many :measurement_groups, :class_name => 'MeasurementGroup', :foreign_key => :sampleID
end

app/models/schema_migration.rb
class SchemaMigration < ActiveRecord::Base



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/description_for_rds_controller.rb
class DescriptionForRdsController < ApplicationController
  def index
    @descriptionForRds = DescriptionForRd.all
  end

  def new
    @descriptionForRd = DescriptionForRd.new
  end

  def edit
  @descriptionForRd = DescriptionForRd.find(params[:id])
  end

  def show
    @descriptionForRd = DescriptionForRd.find(params[:id])
  end

  def create
    @descriptionForRd = DescriptionForRd.new(description_for_rd_params)

    if @descriptionForRd.save
    redirect_to @descriptionForRd
    else
    render 'new'
    end
  end

  def update
  @descriptionForRd = DescriptionForRd.find(params[:id])

  if @descriptionForRd.update(description_for_rd_params)
    redirect_to @descriptionForRd
  else
    render 'edit'
  end
  end

  def destroy
  @descriptionForRd = DescriptionForRd.find(params[:id])
  @descriptionForRd.destroy

  redirect_to devices_path
end



  private
  def description_for_rd_params
    params.require(:description_for_rd).permit(:name, :value, :rdId)
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def index
    @devices = Device.all
  end

  def new
    @device = Device.new
  end

  def edit
  @device = Device.find(params[:id])
  end

  def show
    @device = Device.find(params[:id])
  end

  def create
    @device = Device.new(device_params)

    if @device.save
    redirect_to @device
    else
    render 'new'
    end
  end

  def update
  @device = Device.find(params[:id])

  if @device.update(device_params)
    redirect_to @device
  else
    render 'edit'
  end
  end

  def destroy
  @device = Device.find(params[:id])
  @device.destroy

  redirect_to devices_path
end



  private
  def device_params
    params.require(:device).permit(:name, :manufacturer, :description, :model)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/raw_datums_helper.rb
module RawDatumsHelper
end

app/helpers/researchers_helper.rb
module ResearchersHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/description_for_rds/_form.html.erb
<%= form_for @descriptionForRd do |f| %>

  <% if @descriptionForRd.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@descriptionForRd.errors.count, "error") %> prohibited
        this device from being saved:
      </h2>
      <ul>
        <% @descriptionForRd.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :value %><br>
    <%= f.text_area :value %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/description_for_rds/edit.html.erb
<h1>Изменить данные</h1>

<%= render 'form' %>

<%= link_to 'Назад', description_for_rds_path %>

app/views/description_for_rds/index.html.erb
<h1>Список приборов</h1>

  <td><a class='btn-primary'><%= link_to 'Добавить прибор', new_description_for_rd_path %></a></td>
<td><%= link_to 'Скачать отчет', "/devices.pdf" %></td></br></br></br>

<table class="table table-striped table-condensed">
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th>RDID</th>
  </tr>

  <% @descriptionForRds.each do |device| %>
    <tr>
      <td><%= device.name %></td>
      <td><%= device.value %></td>


      <td><%= link_to 'Показать', description_for_rd_path(device) %></td>
      <td><%= link_to 'Изменить', edit_description_for_rd_path(device) %></td>
      <td><%= link_to 'Удалить', description_for_rd_path(device),
              method: :delete,
              data: { confirm: 'Вы уверены?' } %></td>
   </tr>
  <% end %>
</table>

app/views/description_for_rds/new.html.erb
<%= render 'form' %>

app/views/description_for_rds/show.html.erb
<p>
  <strong>Name</strong>
  <%= @descriptionForRd.name %>
</p>

<p>
  <strong>Value</strong>
  <%= @descriptionForRd.value %>
</p>






<%= link_to 'Назад', description_for_rds_path %> |
<%= link_to 'Изменить', edit_description_for_rd_path(@descriptionForRd) %>