config/routes.rb
Rails.application.routes.draw do
  #resources :attachments
  resources :attachments do
    collection { post :parse }
    collection { post :display_graphics }
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :measurement_groups
  resources :devices
  resources :measurements
  resources :samples
  resources :researchers
  resources :raw_datums
  resources :description_for_rds


  #resources :measurement_groups, shallow: true do
  #  resources :devices
  #end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
    validate :file_size_under_one_mb

  def initialize(params = {})
    @file = params.delete(:file)
    super
    if @file
      self.filename = sanitize_filename(@file.original_filename)
      self.content_type = @file.content_type
      self.file_contents = @file.read
    end
  end

  private

    def sanitize_filename(filename)
      # Get only the filename, not the whole path (for IE)
      # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
      return File.basename(filename)
    end

    NUM_BYTES_IN_MEGABYTE = 1048576
    def file_size_under_one_mb
      if (@file.size.to_f / NUM_BYTES_IN_MEGABYTE) > 1
        errors.add(:file, 'File size cannot be over one megabyte.')
      end
    end
end

app/models/description_for_rd.rb
class DescriptionForRd < ActiveRecord::Base
    self.table_name = 'description_for_rd'
    self.primary_key = :DescriptionForRdID

    belongs_to :raw_datum, :class_name => 'RawDatum', :foreign_key => :rdID
end

app/models/device.rb
class Device < ActiveRecord::Base

    self.primary_key = :deviceID

    has_many :measurement_groups, :class_name => 'MeasurementGroup', :foreign_key => :deviceID
end

app/models/linked.rb
class Linked < ActiveRecord::Base



    belongs_to :measurement, :class_name => 'Measurement', :foreign_key => :measurementID
    belongs_to :measurement_group, :class_name => 'MeasurementGroup', :foreign_key => :groupID
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base

    self.primary_key = :measurementID

    has_many :linkeds, :class_name => 'Linked', :foreign_key => :measurementID
    belongs_to :raw_datum, :class_name => 'RawDatum', :foreign_key => :rpID
    has_many :measurement_description_for_measurements, :class_name => 'MeasurementDescriptionForMeasurement', :foreign_key => :measurementID
end

app/models/measurement_group.rb
class MeasurementGroup < ActiveRecord::Base

    self.primary_key = :groupID

    has_many :linkeds, :class_name => 'Linked', :foreign_key => :groupID
    has_many :description_for_measurement_groups, :class_name => 'DescriptionForMeasurementGroup', :foreign_key => :groupID
    belongs_to :sample, :class_name => 'Sample', :foreign_key => :sampleID
    belongs_to :researcher, :class_name => 'Researcher', :foreign_key => :researcherID
    belongs_to :device, :class_name => 'Device', :foreign_key => :deviceID
    has_many :raw_data, :class_name => 'RawDatum', :foreign_key => :groupID
end

app/models/raw_datum.rb
class RawDatum < ActiveRecord::Base

    self.primary_key = :rdID

    has_many :measurements, :class_name => 'Measurement'
    has_many :description_for_rds, :class_name => 'DescriptionForRd', :foreign_key => :rdID
    belongs_to :measurement_group, :class_name => 'MeasurementGroup', :foreign_key => :groupID
end

app/models/researcher.rb
class Researcher < ActiveRecord::Base

    self.primary_key = :researcherID

    has_many :measurement_groups, :class_name => 'MeasurementGroup', :foreign_key => :researcherID
end

app/models/sample.rb
class Sample < ActiveRecord::Base

    self.primary_key = :sampleID

    has_many :measurement_groups, :class_name => 'MeasurementGroup', :foreign_key => :sampleID
end

app/models/schema_migration.rb
class SchemaMigration < ActiveRecord::Base



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/raw_datums_helper.rb
module RawDatumsHelper
end

app/helpers/researchers_helper.rb
module ResearchersHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_links_ffs.erb
<li><%= link_to 'Исследователь', controller: 'researchers' %></li>
<li><%= link_to "Прибор", controller: 'devices' %></li>
<li><%= link_to "Образец", controller: 'samples' %></li>
<li><%= link_to "Измерение",    controller: 'measurements' %></li>
<li><%= link_to "Группа измерений",    controller: 'measurement_groups' %></li>
<li><%= link_to "Необработанные данные",    controller: 'raw_datums' %></li>

<% if user_signed_in? %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Профиль', edit_user_registration_path %></li>
  <li><%= link_to 'Выйти', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Войти', new_user_session_path %></li>
  <li><%= link_to 'Регистрация', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Главная', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">

      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
        <li><p class="navbar-text navbar-right">
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Введите название группы">
          </div>
          <button type="submit" class="btn btn-default">Найти</button>
        </form>
      </p></li>>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'О нас', page_path('about') %></li>
<% if user_signed_in? %>
<li><%= link_to 'Исследователь', researchers_path %></li>
<%#<li><%= link_to "Прибор", devices_path %> </li>
<li><%= link_to "Образец", samples_path %></li>
<li><%= link_to "Измерение", measurements_path %></li>
<li><%= link_to "Группа измерений", measurement_groups_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Remote access system" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ffs Remote" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <style>
    body {
      background:#FAFAFA !important;
  }</style>
  <body bgcolor="#808080">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>

    <footer class="footer">
      <small>
        Created by
        <a href="http://vk.com/id89261448">Kardashov Dmitry</a>
      </small>
      <nav>
        <ul>
          <%= render 'layouts/navigation_links' %>
        </ul>
      </nav>
    </footer>
  </body>
</html>